baseURL = "https://renanbatista.dev"
languageCode = "en-us"
title = "Renan Batista"
theme="archie"
copyright = "© Athul"
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
[params]
	mode="toggle"
	useCDN=false
	subtitle = ""
  mathjax = true # enable MathJax support
	katex = true # enable KaTeX support

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/rfbatista"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/rfbatista1"

[[menu.main]]
name = "Inicio"
url = "/"
weight = 1

[[menu.main]]
name = "Todos os posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "Sobre"
url = "/sobre"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4
